plugins:
  antillion:
    executor: central_deployment_agent
    source: https://github.com/Antillion/rundeck-cloudify-plugin/archive/master.zip

node_types:
  antillion.rundeck.config:
    derived_from: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: antillion.cfyrundeck.jobs.execute
