plugins:
  # Name could be anything, this name is what appears on the beginning of operation
  # mappings.
  antillion:
    # Could be 'central_deployment_agent' or 'host_agent'.
    # If 'central_deployment_agent', this plugin will be executed on the
    # deployment dedicated agent, other wise it will be executed on the host agent.
    executor: central_deployment_agent

    # URL to archive containing the plugin or name of directory containing
    # the plugin if it is included in the the blueprint directory under the
    # "plugins" directory.
    source: https://github.com/Antillion/rundeck-cloudify-plugin/archive/master.zip

node_types:
  antillion.rundeck.config:
    derived_from: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: antillion.cfyrundeck.jobs.execute
    # properties:
    #   hostname:   { type: string }
    #   api_token:  { type: string }
